require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ReclamacaosController do

  def mock_reclamacao(stubs={})
    @mock_reclamacao ||= mock_model(Reclamacao, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all reclamacaos as @reclamacaos" do
      Reclamacao.stub(:all) { [mock_reclamacao] }
      get :index
      assigns(:reclamacaos).should eq([mock_reclamacao])
    end
  end

  describe "GET show" do
    it "assigns the requested reclamacao as @reclamacao" do
      Reclamacao.stub(:find).with("37") { mock_reclamacao }
      get :show, :id => "37"
      assigns(:reclamacao).should be(mock_reclamacao)
    end
  end

  describe "GET new" do
    it "assigns a new reclamacao as @reclamacao" do
      Reclamacao.stub(:new) { mock_reclamacao }
      get :new
      assigns(:reclamacao).should be(mock_reclamacao)
    end
  end

  describe "GET edit" do
    it "assigns the requested reclamacao as @reclamacao" do
      Reclamacao.stub(:find).with("37") { mock_reclamacao }
      get :edit, :id => "37"
      assigns(:reclamacao).should be(mock_reclamacao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created reclamacao as @reclamacao" do
        Reclamacao.stub(:new).with({'these' => 'params'}) { mock_reclamacao(:save => true) }
        post :create, :reclamacao => {'these' => 'params'}
        assigns(:reclamacao).should be(mock_reclamacao)
      end

      it "redirects to the created reclamacao" do
        Reclamacao.stub(:new) { mock_reclamacao(:save => true) }
        post :create, :reclamacao => {}
        response.should redirect_to(reclamacao_url(mock_reclamacao))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reclamacao as @reclamacao" do
        Reclamacao.stub(:new).with({'these' => 'params'}) { mock_reclamacao(:save => false) }
        post :create, :reclamacao => {'these' => 'params'}
        assigns(:reclamacao).should be(mock_reclamacao)
      end

      it "re-renders the 'new' template" do
        Reclamacao.stub(:new) { mock_reclamacao(:save => false) }
        post :create, :reclamacao => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reclamacao" do
        Reclamacao.stub(:find).with("37") { mock_reclamacao }
        mock_reclamacao.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :reclamacao => {'these' => 'params'}
      end

      it "assigns the requested reclamacao as @reclamacao" do
        Reclamacao.stub(:find) { mock_reclamacao(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:reclamacao).should be(mock_reclamacao)
      end

      it "redirects to the reclamacao" do
        Reclamacao.stub(:find) { mock_reclamacao(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(reclamacao_url(mock_reclamacao))
      end
    end

    describe "with invalid params" do
      it "assigns the reclamacao as @reclamacao" do
        Reclamacao.stub(:find) { mock_reclamacao(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:reclamacao).should be(mock_reclamacao)
      end

      it "re-renders the 'edit' template" do
        Reclamacao.stub(:find) { mock_reclamacao(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reclamacao" do
      Reclamacao.stub(:find).with("37") { mock_reclamacao }
      mock_reclamacao.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the reclamacaos list" do
      Reclamacao.stub(:find) { mock_reclamacao }
      delete :destroy, :id => "1"
      response.should redirect_to(reclamacaos_url)
    end
  end

end
